import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Link href="/">Início</Link>
          <h1 className="title">Filme: {data.title}</h1>
            <p>{data.overview}</p> 
            <img src={`https://image.tmdb.org/t/p/original${data.backdrop_path}`} width="500" />         
      </main>
    </div>
  )
}


export async function getServerSideProps(context){
    const { id } = context.params
    const res = await fetch(`http://localhost:3000/api/movie/${id}`)
    const json = await res.json()


    return {
      props: {
        data: json.data
      }
    }
  }